export const INVENTORY_MOVEMENT_TYPE = {
  ADJUST: 'ADJUST',
  RECEIVE: 'RECEIVE',
  TRANSFER_OUT: 'TRANSFER_OUT',
  TRANSFER_IN: 'TRANSFER_IN',
} as const;

export type InventoryMovementType =
  (typeof INVENTORY_MOVEMENT_TYPE)[keyof typeof INVENTORY_MOVEMENT_TYPE];

export const INVENTORY_REFERENCE_TYPE = {
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
} as const;

export const STOCK_ADJUSTMENT_TYPE = {
  CORRECTION: 'CORRECTION',
  OPENING_BALANCE: 'OPENING_BALANCE',
  MANUAL_RECEIPT: 'MANUAL_RECEIPT',
} as const;

export type StockAdjustmentType =
  (typeof STOCK_ADJUSTMENT_TYPE)[keyof typeof STOCK_ADJUSTMENT_TYPE];

export const STOCK_ADJUSTMENT_REASON = {
  MANUAL: 'MANUAL',
  COUNT_CORRECTION: 'COUNT_CORRECTION',
  INITIAL_STOCK: 'INITIAL_STOCK',
  EXTERNAL_RECEIPT: 'EXTERNAL_RECEIPT',
} as const;

export type StockAdjustmentReason =
  (typeof STOCK_ADJUSTMENT_REASON)[keyof typeof STOCK_ADJUSTMENT_REASON];
