export const FULFILLMENT_STATUS = {
  PENDING: 'PENDING',
  PICKING: 'PICKING',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  RETURNING_TO_WAREHOUSE: 'RETURNING_TO_WAREHOUSE',
  RETURNED_TO_WAREHOUSE: 'RETURNED_TO_WAREHOUSE',
  CANCELLED: 'CANCELLED',
} as const;

export const FULFILLMENT_ACTION = {
  PICK: 'PICK',
  PACK: 'PACK',
  SHIP: 'SHIP',
  DELIVER: 'DELIVER',
  FAIL_DELIVERY: 'FAIL_DELIVERY',
  RECEIVE_RETURN: 'RECEIVE_RETURN',
} as const;

export const RETURN_CONDITION = {
  SELLABLE: 'SELLABLE',
  DAMAGED: 'DAMAGED',
  MISSING: 'MISSING',
} as const;

export const FULFILLMENT_TRANSACTION = {
  MAX_WAIT_MS: 10_000,
  TIMEOUT_MS: 30_000,
  MAX_SERIALIZATION_RETRIES: 3,
} as const;
