export const ORDER_STATUS = {
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  PICKING: 'PICKING',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const ORDER_STATUS_GROUP = {
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
} as const;

export const ORDER_STATUS_BY_GROUP: Record<string, string[]> = {
  [ORDER_STATUS_GROUP.PENDING_CONFIRMATION]: [ORDER_STATUS.PENDING_CONFIRMATION],
  [ORDER_STATUS_GROUP.CONFIRMED]: [ORDER_STATUS.CONFIRMED],
  [ORDER_STATUS_GROUP.IN_TRANSIT]: [
    ORDER_STATUS.PICKING,
    ORDER_STATUS.PACKED,
    ORDER_STATUS.SHIPPED,
  ],
  [ORDER_STATUS_GROUP.DELIVERED]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.COMPLETED],
};

export { PAYMENT_STATUS as ORDER_PAYMENT_STATUS } from '../payment/payment.constants';

export const ORDER_FULFILLMENT_STATUS = {
  PENDING: 'PENDING',
  PICKING: 'PICKING',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  RETURNED: 'RETURNED',
  CANCELLED: 'CANCELLED',
} as const;

export const ORDER_CHANNEL = {
  WEB: 'WEB',
  STORE: 'STORE',
} as const;

export const ORDER_AUDIT_ACTION = {
  PLACE: 'order.place',
  CONFIRM: 'order.confirm',
  CANCEL: 'order.cancel',
  COMPLETE_MANUALLY: 'order.complete-manually',
} as const;

export const ORDER_TRANSITION = {
  CONFIRM: 'CONFIRM',
  CANCEL: 'CANCEL',
  COMPLETE_MANUALLY: 'COMPLETE_MANUALLY',
} as const;

export const ORDER_TRANSACTION = {
  MAX_WAIT_MS: 10_000,
  TIMEOUT_MS: 30_000,
} as const;
