BEGIN;

SELECT pg_advisory_xact_lock(hashtext('dctd:add_sprint3_checkout_foundation'));

CREATE TABLE public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE,
  customer_no VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  normalized_email VARCHAR(255),
  phone VARCHAR(32),
  normalized_phone VARCHAR(32),
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  marketing_consent BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT customers_identity_check CHECK (normalized_email IS NOT NULL OR normalized_phone IS NOT NULL),
  CONSTRAINT customers_status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX customers_normalized_email_key ON public.customers(normalized_email) WHERE normalized_email IS NOT NULL;
CREATE UNIQUE INDEX customers_normalized_phone_key ON public.customers(normalized_phone) WHERE normalized_phone IS NOT NULL;
CREATE INDEX customers_status_created_at_idx ON public.customers(status, created_at);

CREATE TABLE public.customer_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  address_type VARCHAR(24) NOT NULL DEFAULT 'SHIPPING',
  recipient VARCHAR(255) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  address_line VARCHAR(500) NOT NULL,
  ward VARCHAR(255),
  district VARCHAR(255),
  province_code VARCHAR(32) NOT NULL,
  postal_code VARCHAR(20),
  country_code CHAR(2) NOT NULL DEFAULT 'VN',
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT customer_addresses_type_check CHECK (address_type IN ('SHIPPING', 'BILLING')),
  CONSTRAINT customer_addresses_status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT customer_addresses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX customer_addresses_customer_id_status_idx ON public.customer_addresses(customer_id, status);
CREATE UNIQUE INDEX customer_addresses_one_default_per_type_key
  ON public.customer_addresses(customer_id, address_type)
  WHERE is_default AND status = 'ACTIVE';

CREATE TABLE public.carts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  customer_id BIGINT,
  anonymous_token_hash CHAR(64),
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  currency_code CHAR(3) NOT NULL DEFAULT 'VND',
  branch_id BIGINT,
  expires_at TIMESTAMPTZ(6),
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT carts_owner_shape_check CHECK (
    (anonymous_token_hash IS NOT NULL AND user_id IS NULL AND customer_id IS NULL)
    OR (anonymous_token_hash IS NULL AND (user_id IS NOT NULL OR customer_id IS NOT NULL))
  ),
  CONSTRAINT carts_status_check CHECK (status IN ('ACTIVE', 'CONVERTED', 'ABANDONED', 'EXPIRED')),
  CONSTRAINT carts_currency_check CHECK (currency_code = 'VND'),
  CONSTRAINT carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT carts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT carts_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX carts_active_user_key ON public.carts(user_id) WHERE status = 'ACTIVE' AND user_id IS NOT NULL;
CREATE UNIQUE INDEX carts_active_customer_key ON public.carts(customer_id) WHERE status = 'ACTIVE' AND customer_id IS NOT NULL;
CREATE UNIQUE INDEX carts_active_anonymous_key ON public.carts(anonymous_token_hash) WHERE status = 'ACTIVE' AND anonymous_token_hash IS NOT NULL;
CREATE INDEX carts_user_id_status_idx ON public.carts(user_id, status);
CREATE INDEX carts_customer_id_status_idx ON public.carts(customer_id, status);
CREATE INDEX carts_anonymous_token_hash_status_idx ON public.carts(anonymous_token_hash, status);
CREATE INDEX carts_branch_id_idx ON public.carts(branch_id);
CREATE INDEX carts_expires_at_idx ON public.carts(expires_at);

CREATE TABLE public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id BIGINT NOT NULL,
  product_variant_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  price_seen_at TIMESTAMPTZ(6),
  unit_price_preview DECIMAL(19,2),
  metadata_json JSONB,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cart_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT cart_items_price_check CHECK (unit_price_preview IS NULL OR unit_price_preview >= 0),
  CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT cart_items_product_variant_id_fkey FOREIGN KEY (product_variant_id) REFERENCES public.product_variants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT cart_items_cart_id_product_variant_id_key UNIQUE (cart_id, product_variant_id)
);
CREATE INDEX cart_items_product_variant_id_idx ON public.cart_items(product_variant_id);

CREATE TABLE public.shipping_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  province_codes VARCHAR(32)[] NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  priority INTEGER NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT shipping_zones_provinces_check CHECK (cardinality(province_codes) > 0),
  CONSTRAINT shipping_zones_status_check CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE INDEX shipping_zones_status_priority_idx ON public.shipping_zones(status, priority);
CREATE INDEX shipping_zones_province_codes_gin_idx ON public.shipping_zones USING GIN(province_codes);

CREATE TABLE public.shipping_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id BIGINT NOT NULL,
  branch_id BIGINT,
  min_weight_grams INTEGER NOT NULL DEFAULT 0,
  max_weight_grams INTEGER,
  min_subtotal DECIMAL(19,2) NOT NULL DEFAULT 0,
  max_subtotal DECIMAL(19,2),
  base_fee DECIMAL(19,2) NOT NULL,
  per_kg_fee DECIMAL(19,2) NOT NULL DEFAULT 0,
  free_shipping_threshold DECIMAL(19,2),
  eta_min_days INTEGER NOT NULL,
  eta_max_days INTEGER NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT shipping_rates_status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT shipping_rates_weight_check CHECK (min_weight_grams >= 0 AND (max_weight_grams IS NULL OR max_weight_grams >= min_weight_grams)),
  CONSTRAINT shipping_rates_subtotal_check CHECK (min_subtotal >= 0 AND (max_subtotal IS NULL OR max_subtotal >= min_subtotal)),
  CONSTRAINT shipping_rates_fee_check CHECK (base_fee >= 0 AND per_kg_fee >= 0 AND (free_shipping_threshold IS NULL OR free_shipping_threshold >= 0)),
  CONSTRAINT shipping_rates_eta_check CHECK (eta_min_days >= 0 AND eta_max_days >= eta_min_days),
  CONSTRAINT shipping_rates_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.shipping_zones(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT shipping_rates_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX shipping_rates_zone_id_status_idx ON public.shipping_rates(zone_id, status);
CREATE INDEX shipping_rates_branch_id_status_idx ON public.shipping_rates(branch_id, status);

CREATE TABLE public.checkout_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkout_token VARCHAR(100) NOT NULL UNIQUE,
  cart_id BIGINT NOT NULL,
  customer_id BIGINT,
  branch_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  shipping_rate_id BIGINT,
  status VARCHAR(24) NOT NULL DEFAULT 'QUOTED',
  currency_code CHAR(3) NOT NULL DEFAULT 'VND',
  prices_include_tax BOOLEAN NOT NULL DEFAULT TRUE,
  item_subtotal DECIMAL(19,2) NOT NULL,
  shipping_total DECIMAL(19,2) NOT NULL,
  grand_total DECIMAL(19,2) NOT NULL,
  eta_min_days INTEGER NOT NULL,
  eta_max_days INTEGER NOT NULL,
  recipient_snapshot JSONB NOT NULL,
  shipping_rule_snapshot JSONB NOT NULL,
  idempotency_key VARCHAR(150) NOT NULL UNIQUE,
  request_hash CHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ(6) NOT NULL,
  confirmed_at TIMESTAMPTZ(6),
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT checkout_sessions_status_check CHECK (status IN ('QUOTED', 'CONFIRMED', 'EXPIRED', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT checkout_sessions_currency_check CHECK (currency_code = 'VND'),
  CONSTRAINT checkout_sessions_money_check CHECK (item_subtotal >= 0 AND shipping_total >= 0 AND grand_total = item_subtotal + shipping_total),
  CONSTRAINT checkout_sessions_eta_check CHECK (eta_min_days >= 0 AND eta_max_days >= eta_min_days),
  CONSTRAINT checkout_sessions_confirmed_check CHECK ((status = 'QUOTED' AND confirmed_at IS NULL) OR status <> 'QUOTED'),
  CONSTRAINT checkout_sessions_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES public.carts(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT checkout_sessions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT checkout_sessions_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT checkout_sessions_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT checkout_sessions_shipping_rate_id_fkey FOREIGN KEY (shipping_rate_id) REFERENCES public.shipping_rates(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX checkout_sessions_cart_id_status_idx ON public.checkout_sessions(cart_id, status);
CREATE INDEX checkout_sessions_customer_id_created_at_idx ON public.checkout_sessions(customer_id, created_at);
CREATE INDEX checkout_sessions_branch_id_status_idx ON public.checkout_sessions(branch_id, status);
CREATE INDEX checkout_sessions_expires_at_status_idx ON public.checkout_sessions(expires_at, status);

CREATE TABLE public.checkout_session_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkout_session_id BIGINT NOT NULL,
  cart_item_id BIGINT,
  product_variant_id BIGINT NOT NULL,
  item_type VARCHAR(24) NOT NULL DEFAULT 'STANDARD',
  sku_snapshot VARCHAR(64) NOT NULL,
  name_snapshot VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(19,2) NOT NULL,
  line_total DECIMAL(19,2) NOT NULL,
  component_snapshot JSONB,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT checkout_session_items_type_check CHECK (item_type IN ('STANDARD', 'BUNDLE')),
  CONSTRAINT checkout_session_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT checkout_session_items_money_check CHECK (unit_price >= 0 AND line_total = unit_price * quantity),
  CONSTRAINT checkout_session_items_checkout_session_id_fkey FOREIGN KEY (checkout_session_id) REFERENCES public.checkout_sessions(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT checkout_session_items_cart_item_id_fkey FOREIGN KEY (cart_item_id) REFERENCES public.cart_items(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT checkout_session_items_product_variant_id_fkey FOREIGN KEY (product_variant_id) REFERENCES public.product_variants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT checkout_session_items_checkout_session_id_product_variant_id_key UNIQUE (checkout_session_id, product_variant_id)
);
CREATE INDEX checkout_session_items_cart_item_id_idx ON public.checkout_session_items(cart_item_id);
CREATE INDEX checkout_session_items_product_variant_id_idx ON public.checkout_session_items(product_variant_id);

CREATE TABLE public.inventory_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkout_session_id BIGINT NOT NULL UNIQUE,
  warehouse_id BIGINT NOT NULL,
  reservation_token VARCHAR(100) NOT NULL UNIQUE,
  idempotency_key VARCHAR(150) NOT NULL UNIQUE,
  request_hash CHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  expires_at TIMESTAMPTZ(6) NOT NULL,
  committed_at TIMESTAMPTZ(6),
  released_at TIMESTAMPTZ(6),
  release_reason VARCHAR(500),
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT inventory_reservations_status_check CHECK (status IN ('ACTIVE', 'COMMITTED', 'RELEASED', 'EXPIRED')),
  CONSTRAINT inventory_reservations_state_check CHECK (
    (status = 'ACTIVE' AND committed_at IS NULL AND released_at IS NULL)
    OR (status = 'COMMITTED' AND committed_at IS NOT NULL AND released_at IS NULL)
    OR (status IN ('RELEASED', 'EXPIRED') AND committed_at IS NULL AND released_at IS NOT NULL AND NULLIF(BTRIM(release_reason), '') IS NOT NULL)
  ),
  CONSTRAINT inventory_reservations_checkout_session_id_fkey FOREIGN KEY (checkout_session_id) REFERENCES public.checkout_sessions(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT inventory_reservations_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX inventory_reservations_warehouse_id_status_idx ON public.inventory_reservations(warehouse_id, status);
CREATE INDEX inventory_reservations_status_expires_at_id_idx ON public.inventory_reservations(status, expires_at, id);

CREATE TABLE public.inventory_reservation_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_id BIGINT NOT NULL,
  product_variant_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  source_breakdown_json JSONB,
  CONSTRAINT inventory_reservation_items_quantity_check CHECK (quantity > 0),
  CONSTRAINT inventory_reservation_items_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.inventory_reservations(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT inventory_reservation_items_product_variant_id_fkey FOREIGN KEY (product_variant_id) REFERENCES public.product_variants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT inventory_reservation_items_reservation_id_product_variant_id_key UNIQUE (reservation_id, product_variant_id)
);
CREATE INDEX inventory_reservation_items_product_variant_id_idx ON public.inventory_reservation_items(product_variant_id);

CREATE TABLE public.system_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key VARCHAR(150) NOT NULL UNIQUE,
  value_json JSONB NOT NULL,
  value_type VARCHAR(24) NOT NULL,
  description VARCHAR(500),
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  version BIGINT NOT NULL DEFAULT 0,
  updated_by BIGINT,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT system_settings_value_type_check CHECK (value_type IN ('INTEGER', 'DECIMAL', 'BOOLEAN', 'STRING', 'JSON')),
  CONSTRAINT system_settings_status_check CHECK (status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX system_settings_status_key_idx ON public.system_settings(status, key);

INSERT INTO public.system_settings(key, value_json, value_type, description, is_public, status)
VALUES ('checkout.reservation_ttl_minutes', '30'::jsonb, 'INTEGER', 'Số phút giữ tồn sau khi xác nhận checkout', FALSE, 'ACTIVE')
ON CONFLICT (key) DO NOTHING;

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_rates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkout_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkout_session_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_reservation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON public.customers, public.customer_addresses, public.carts,
  public.cart_items, public.shipping_zones, public.shipping_rates, public.checkout_sessions,
  public.checkout_session_items, public.inventory_reservations,
  public.inventory_reservation_items, public.system_settings FROM anon, authenticated;

COMMIT;
