BEGIN;

SELECT pg_advisory_xact_lock(hashtext('dctd:add_order_foundation'));

CREATE SEQUENCE public.order_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(32) NOT NULL UNIQUE,
  idempotency_key VARCHAR(150) NOT NULL UNIQUE,
  request_hash CHAR(64) NOT NULL,
  checkout_session_id BIGINT NOT NULL UNIQUE,
  reservation_id BIGINT NOT NULL UNIQUE,
  customer_id BIGINT NOT NULL,
  branch_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  channel VARCHAR(24) NOT NULL DEFAULT 'WEB',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_CONFIRMATION',
  payment_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  fulfillment_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  currency_code CHAR(3) NOT NULL DEFAULT 'VND',
  prices_include_tax BOOLEAN NOT NULL DEFAULT TRUE,
  subtotal DECIMAL(19,2) NOT NULL,
  discount_total DECIMAL(19,2) NOT NULL DEFAULT 0,
  shipping_total DECIMAL(19,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(19,2) NOT NULL DEFAULT 0,
  grand_total DECIMAL(19,2) NOT NULL,
  customer_note VARCHAR(1000),
  internal_note VARCHAR(2000),
  utm_json JSONB,
  placed_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cancelled_at TIMESTAMPTZ(6),
  cancel_reason VARCHAR(500),
  completed_at TIMESTAMPTZ(6),
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT orders_checkout_session_id_fkey FOREIGN KEY (checkout_session_id) REFERENCES public.checkout_sessions(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT orders_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.inventory_reservations(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT orders_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT orders_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT orders_channel_check CHECK (channel IN ('WEB', 'STORE')),
  CONSTRAINT orders_status_check CHECK (status IN ('PENDING_CONFIRMATION', 'CONFIRMED', 'PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT orders_payment_status_check CHECK (payment_status IN ('PENDING', 'AWAITING_CONFIRMATION', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED')),
  CONSTRAINT orders_fulfillment_status_check CHECK (fulfillment_status IN ('PENDING', 'PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'FAILED', 'RETURNED', 'CANCELLED')),
  CONSTRAINT orders_currency_check CHECK (currency_code = 'VND'),
  CONSTRAINT orders_money_check CHECK (
    subtotal >= 0 AND discount_total >= 0 AND shipping_total >= 0 AND tax_total >= 0
    AND grand_total = subtotal - discount_total + shipping_total
  ),
  CONSTRAINT orders_terminal_timestamp_check CHECK (
    (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
    OR (status = 'COMPLETED' AND completed_at IS NOT NULL)
    OR status NOT IN ('CANCELLED', 'COMPLETED')
  )
);
CREATE INDEX orders_customer_id_placed_at_id_idx ON public.orders(customer_id, placed_at DESC, id DESC);
CREATE INDEX orders_branch_id_status_placed_at_id_idx ON public.orders(branch_id, status, placed_at DESC, id DESC);
CREATE INDEX orders_warehouse_id_fulfillment_status_idx ON public.orders(warehouse_id, fulfillment_status);
CREATE INDEX orders_payment_status_placed_at_idx ON public.orders(payment_status, placed_at);

CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  line_no INTEGER NOT NULL,
  product_variant_id BIGINT NOT NULL,
  product_bundle_id BIGINT,
  item_type VARCHAR(24) NOT NULL DEFAULT 'STANDARD',
  sku_snapshot VARCHAR(64) NOT NULL,
  product_name_snapshot VARCHAR(255) NOT NULL,
  variant_name_snapshot VARCHAR(255) NOT NULL,
  attributes_snapshot JSONB,
  image_url_snapshot TEXT,
  quantity INTEGER NOT NULL,
  list_unit_price DECIMAL(19,2) NOT NULL,
  discount_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
  final_unit_price DECIMAL(19,2) NOT NULL,
  tax_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
  line_total DECIMAL(19,2) NOT NULL,
  unit_cost_snapshot DECIMAL(19,2),
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT order_items_product_variant_id_fkey FOREIGN KEY (product_variant_id) REFERENCES public.product_variants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT order_items_product_bundle_id_fkey FOREIGN KEY (product_bundle_id) REFERENCES public.product_bundles(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT order_items_order_id_line_no_key UNIQUE (order_id, line_no),
  CONSTRAINT order_items_line_check CHECK (line_no > 0 AND quantity > 0),
  CONSTRAINT order_items_type_check CHECK (
    (item_type = 'STANDARD' AND product_bundle_id IS NULL)
    OR (item_type = 'BUNDLE' AND product_bundle_id IS NOT NULL)
  ),
  CONSTRAINT order_items_money_check CHECK (
    list_unit_price >= 0 AND discount_amount >= 0 AND final_unit_price >= 0 AND tax_amount >= 0
    AND final_unit_price = list_unit_price - discount_amount
    AND line_total = final_unit_price * quantity
  )
);
CREATE INDEX order_items_product_variant_id_idx ON public.order_items(product_variant_id);
CREATE INDEX order_items_product_bundle_id_idx ON public.order_items(product_bundle_id);

CREATE TABLE public.order_item_components (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_item_id BIGINT NOT NULL,
  bundle_item_id BIGINT,
  component_variant_id BIGINT NOT NULL,
  sku_snapshot VARCHAR(64) NOT NULL,
  name_snapshot VARCHAR(255) NOT NULL,
  quantity_per_bundle INTEGER NOT NULL,
  total_quantity INTEGER NOT NULL,
  unit_cost_snapshot DECIMAL(19,2),
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_item_components_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT order_item_components_bundle_item_id_fkey FOREIGN KEY (bundle_item_id) REFERENCES public.bundle_items(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT order_item_components_component_variant_id_fkey FOREIGN KEY (component_variant_id) REFERENCES public.product_variants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT order_item_components_order_item_id_component_variant_id_key UNIQUE (order_item_id, component_variant_id),
  CONSTRAINT order_item_components_quantity_check CHECK (quantity_per_bundle > 0 AND total_quantity > 0),
  CONSTRAINT order_item_components_cost_check CHECK (unit_cost_snapshot IS NULL OR unit_cost_snapshot >= 0)
);
CREATE INDEX order_item_components_bundle_item_id_idx ON public.order_item_components(bundle_item_id);
CREATE INDEX order_item_components_component_variant_id_idx ON public.order_item_components(component_variant_id);

CREATE TABLE public.order_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  address_type VARCHAR(24) NOT NULL DEFAULT 'SHIPPING',
  recipient_name VARCHAR(255) NOT NULL,
  recipient_phone VARCHAR(32) NOT NULL,
  recipient_email VARCHAR(255),
  address_line VARCHAR(500) NOT NULL,
  ward_code VARCHAR(32),
  ward_name VARCHAR(255),
  district_code VARCHAR(32),
  district_name VARCHAR(255),
  province_code VARCHAR(32) NOT NULL,
  province_name VARCHAR(255) NOT NULL,
  postal_code VARCHAR(20),
  country_code CHAR(2) NOT NULL DEFAULT 'VN',
  CONSTRAINT order_addresses_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT order_addresses_order_id_address_type_key UNIQUE (order_id, address_type),
  CONSTRAINT order_addresses_type_check CHECK (address_type IN ('SHIPPING', 'BILLING')),
  CONSTRAINT order_addresses_country_check CHECK (country_code = 'VN')
);
CREATE INDEX order_addresses_recipient_name_idx ON public.order_addresses(recipient_name);
CREATE INDEX order_addresses_recipient_phone_idx ON public.order_addresses(recipient_phone);
CREATE INDEX order_addresses_recipient_email_idx ON public.order_addresses(recipient_email);

CREATE TABLE public.order_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL,
  sequence_no INTEGER NOT NULL,
  from_status VARCHAR(32),
  to_status VARCHAR(32) NOT NULL,
  reason VARCHAR(500),
  actor_type VARCHAR(24) NOT NULL,
  actor_id BIGINT,
  request_id VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT order_status_history_order_id_sequence_no_key UNIQUE (order_id, sequence_no),
  CONSTRAINT order_status_history_sequence_check CHECK (sequence_no > 0),
  CONSTRAINT order_status_history_actor_type_check CHECK (actor_type IN ('GUEST', 'CUSTOMER', 'USER', 'SYSTEM'))
);
CREATE INDEX order_status_history_order_id_created_at_idx ON public.order_status_history(order_id, created_at);
CREATE INDEX order_status_history_request_id_idx ON public.order_status_history(request_id);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_item_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.orders, public.order_items, public.order_item_components, public.order_addresses, public.order_status_history FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.order_number_seq FROM anon, authenticated;

COMMIT;
