-- D43: preserve historical UUIDs in legacy_id while moving all entity PK/FK
-- columns to database-generated BIGINT identities. Public APIs serialize these
-- values as decimal strings so JavaScript clients never lose integer precision.
BEGIN;

SELECT pg_advisory_xact_lock(hashtext('dctd:migrate_uuid_ids_to_bigint_identity'));

CREATE TEMP TABLE _id_tables (table_name text PRIMARY KEY) ON COMMIT DROP;
INSERT INTO _id_tables (table_name)
SELECT c.relname
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_attribute a ON a.attrelid = c.oid AND a.attname = 'id' AND NOT a.attisdropped
JOIN pg_type t ON t.oid = a.atttypid
WHERE n.nspname = 'public'
  AND c.relkind = 'r'
  AND t.typname = 'uuid';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM _id_tables WHERE table_name = 'users') THEN
    RAISE EXCEPTION 'Expected UUID schema was not found; refusing partial ID migration';
  END IF;
END $$;

CREATE TEMP TABLE _fk_map ON COMMIT DROP AS
SELECT
  con.oid AS constraint_oid,
  con.conname AS constraint_name,
  child.relname AS child_table,
  child_col.attname AS child_column,
  child_col.attnotnull AS child_not_null,
  parent.relname AS parent_table,
  pg_get_constraintdef(con.oid, true) AS constraint_definition
FROM pg_constraint con
JOIN pg_class child ON child.oid = con.conrelid
JOIN pg_namespace child_ns ON child_ns.oid = child.relnamespace
JOIN pg_class parent ON parent.oid = con.confrelid
JOIN pg_attribute child_col
  ON child_col.attrelid = child.oid AND child_col.attnum = con.conkey[1]
WHERE con.contype = 'f'
  AND child_ns.nspname = 'public'
  AND parent.relname IN (SELECT table_name FROM _id_tables)
  AND con.confkey = ARRAY[
    (SELECT attnum FROM pg_attribute WHERE attrelid = parent.oid AND attname = 'id')
  ]::smallint[];

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint con
    JOIN pg_class parent ON parent.oid = con.confrelid
    WHERE con.contype = 'f'
      AND parent.relname IN (SELECT table_name FROM _id_tables)
      AND (array_length(con.conkey, 1) <> 1 OR array_length(con.confkey, 1) <> 1)
  ) THEN
    RAISE EXCEPTION 'Composite foreign key to an entity id is not supported by D43';
  END IF;
END $$;

CREATE TEMP TABLE _replaced_columns ON COMMIT DROP AS
SELECT table_name, 'id'::text AS column_name FROM _id_tables
UNION
SELECT child_table, child_column FROM _fk_map;

CREATE TEMP TABLE _dependent_constraints ON COMMIT DROP AS
SELECT DISTINCT
  con.conname AS constraint_name,
  tbl.relname AS table_name,
  pg_get_constraintdef(con.oid, true) AS constraint_definition
FROM pg_constraint con
JOIN pg_class tbl ON tbl.oid = con.conrelid
JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
JOIN _replaced_columns replaced ON replaced.table_name = tbl.relname
JOIN pg_attribute col
  ON col.attrelid = tbl.oid
 AND col.attname = replaced.column_name
 AND col.attnum = ANY(con.conkey)
WHERE ns.nspname = 'public'
  AND con.contype NOT IN ('f', 'p');

CREATE TEMP TABLE _dependent_indexes ON COMMIT DROP AS
SELECT DISTINCT
  idx.relname AS index_name,
  pg_get_indexdef(i.indexrelid) AS index_definition
FROM pg_index i
JOIN pg_class tbl ON tbl.oid = i.indrelid
JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
JOIN pg_class idx ON idx.oid = i.indexrelid
JOIN _replaced_columns replaced ON replaced.table_name = tbl.relname
JOIN pg_attribute col
  ON col.attrelid = tbl.oid
 AND col.attname = replaced.column_name
 AND col.attnum = ANY(i.indkey)
WHERE ns.nspname = 'public'
  AND NOT i.indisprimary
  AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = i.indexrelid);

DO $$
DECLARE row record;
BEGIN
  FOR row IN
    SELECT DISTINCT table_name FROM (
      SELECT table_name FROM _id_tables
      UNION SELECT child_table FROM _fk_map
    ) affected
  LOOP
    EXECUTE format('LOCK TABLE public.%I IN ACCESS EXCLUSIVE MODE', row.table_name);
    EXECUTE format('ALTER TABLE public.%I DISABLE TRIGGER USER', row.table_name);
  END LOOP;
END $$;

DO $$
DECLARE row record;
BEGIN
  FOR row IN SELECT table_name FROM _id_tables ORDER BY table_name LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ADD COLUMN id__bigint BIGINT GENERATED BY DEFAULT AS IDENTITY',
      row.table_name
    );
  END LOOP;

  FOR row IN SELECT DISTINCT child_table, child_column FROM _fk_map ORDER BY child_table, child_column LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ADD COLUMN %I BIGINT',
      row.child_table,
      row.child_column || '__bigint'
    );
  END LOOP;

  FOR row IN SELECT * FROM _fk_map ORDER BY child_table, child_column LOOP
    EXECUTE format(
      'UPDATE public.%I child SET %I = parent.id__bigint FROM public.%I parent WHERE child.%I = parent.id',
      row.child_table,
      row.child_column || '__bigint',
      row.parent_table,
      row.child_column
    );
    IF row.child_not_null AND EXISTS (
      SELECT 1 FROM pg_attribute
      WHERE attrelid = format('public.%I', row.child_table)::regclass
        AND attname = row.child_column || '__bigint'
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN %I SET NOT NULL',
        row.child_table,
        row.child_column || '__bigint'
      );
    END IF;
  END LOOP;
END $$;

ALTER TABLE public.audit_logs
  ALTER COLUMN entity_id TYPE TEXT USING entity_id::text;
ALTER TABLE public.inventory_movements
  ALTER COLUMN reference_id TYPE TEXT USING reference_id::text;

DO $$
DECLARE row record;
BEGIN
  FOR row IN SELECT * FROM _fk_map ORDER BY child_table, constraint_name LOOP
    EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', row.child_table, row.constraint_name);
  END LOOP;
  FOR row IN SELECT * FROM _dependent_constraints ORDER BY table_name, constraint_name LOOP
    EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', row.table_name, row.constraint_name);
  END LOOP;
  FOR row IN SELECT * FROM _dependent_indexes ORDER BY index_name LOOP
    EXECUTE format('DROP INDEX public.%I', row.index_name);
  END LOOP;
  FOR row IN
    SELECT tbl.relname AS table_name, con.conname AS constraint_name
    FROM pg_constraint con
    JOIN pg_class tbl ON tbl.oid = con.conrelid
    JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
    WHERE ns.nspname = 'public'
      AND con.contype = 'p'
      AND tbl.relname IN (SELECT table_name FROM _id_tables)
    ORDER BY tbl.relname
  LOOP
    EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', row.table_name, row.constraint_name);
  END LOOP;

  FOR row IN SELECT DISTINCT child_table, child_column FROM _fk_map ORDER BY child_table, child_column LOOP
    EXECUTE format('ALTER TABLE public.%I DROP COLUMN %I', row.child_table, row.child_column);
    EXECUTE format(
      'ALTER TABLE public.%I RENAME COLUMN %I TO %I',
      row.child_table,
      row.child_column || '__bigint',
      row.child_column
    );
  END LOOP;

  FOR row IN SELECT table_name FROM _id_tables ORDER BY table_name LOOP
    EXECUTE format('ALTER TABLE public.%I RENAME COLUMN id TO legacy_id', row.table_name);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN legacy_id DROP NOT NULL', row.table_name);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN legacy_id DROP DEFAULT', row.table_name);
    EXECUTE format('ALTER TABLE public.%I RENAME COLUMN id__bigint TO id', row.table_name);
    EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id SET NOT NULL', row.table_name);
    EXECUTE format('ALTER TABLE public.%I ADD PRIMARY KEY (id)', row.table_name);
    EXECUTE format(
      'ALTER TABLE public.%I ADD CONSTRAINT %I UNIQUE (legacy_id)',
      row.table_name,
      row.table_name || '_legacy_id_key'
    );
  END LOOP;

  FOR row IN SELECT * FROM _dependent_constraints ORDER BY table_name, constraint_name LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ADD CONSTRAINT %I %s',
      row.table_name,
      row.constraint_name,
      row.constraint_definition
    );
  END LOOP;
  FOR row IN SELECT * FROM _dependent_indexes ORDER BY index_name LOOP
    EXECUTE row.index_definition;
  END LOOP;
  FOR row IN SELECT * FROM _fk_map ORDER BY child_table, constraint_name LOOP
    EXECUTE format(
      'ALTER TABLE public.%I ADD CONSTRAINT %I %s',
      row.child_table,
      row.constraint_name,
      row.constraint_definition
    );
  END LOOP;
END $$;

DO $$
DECLARE row record;
BEGIN
  FOR row IN
    SELECT DISTINCT table_name FROM (
      SELECT table_name FROM _id_tables
      UNION SELECT child_table FROM _fk_map
    ) affected
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE TRIGGER USER', row.table_name);
  END LOOP;
END $$;

COMMIT;
