BEGIN;

SELECT pg_advisory_xact_lock(hashtext('dctd:add_payment_foundation'));

ALTER TABLE public.orders DROP CONSTRAINT orders_payment_status_check;
ALTER TABLE public.orders ADD CONSTRAINT orders_payment_status_check
  CHECK (payment_status IN ('PENDING', 'AWAITING_CONFIRMATION', 'NEED_REVIEW', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED'));

CREATE TABLE public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE,
  payment_ref VARCHAR(64) NOT NULL UNIQUE,
  method VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  expected_amount DECIMAL(19,2) NOT NULL,
  received_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
  currency_code CHAR(3) NOT NULL DEFAULT 'VND',
  expires_at TIMESTAMPTZ(6),
  confirmed_by BIGINT,
  confirmed_at TIMESTAMPTZ(6),
  failure_reason VARCHAR(500),
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT payments_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT payments_method_check CHECK (method IN ('BANK_TRANSFER', 'COD')),
  CONSTRAINT payments_status_check CHECK (status IN ('PENDING', 'AWAITING_CONFIRMATION', 'NEED_REVIEW', 'SUCCESS', 'FAILED', 'CANCELLED')),
  CONSTRAINT payments_currency_check CHECK (currency_code = 'VND'),
  CONSTRAINT payments_amount_check CHECK (expected_amount > 0 AND received_amount >= 0),
  CONSTRAINT payments_expiry_check CHECK (
    (method = 'BANK_TRANSFER' AND (status <> 'PENDING' OR expires_at IS NOT NULL))
    OR method = 'COD'
  ),
  CONSTRAINT payments_confirmation_check CHECK (
    (status = 'SUCCESS' AND confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL AND received_amount = expected_amount)
    OR (status <> 'SUCCESS' AND confirmed_at IS NULL)
  )
);
CREATE INDEX payments_status_created_at_id_idx ON public.payments(status, created_at DESC, id DESC);
CREATE INDEX payments_method_status_expires_at_idx ON public.payments(method, status, expires_at);
CREATE INDEX payments_confirmed_by_idx ON public.payments(confirmed_by);

CREATE TABLE public.payment_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT NOT NULL,
  transaction_type VARCHAR(32) NOT NULL,
  provider VARCHAR(64),
  external_id VARCHAR(255),
  external_event_id VARCHAR(255),
  idempotency_key VARCHAR(150) NOT NULL UNIQUE,
  request_hash CHAR(64) NOT NULL,
  amount DECIMAL(19,2) NOT NULL,
  currency_code CHAR(3) NOT NULL,
  status VARCHAR(32) NOT NULL,
  raw_payload_redacted JSONB,
  occurred_at TIMESTAMPTZ(6) NOT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payment_transactions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT payment_transactions_type_check CHECK (transaction_type IN ('CREATED', 'EVIDENCE_SUBMITTED', 'CONFIRMED', 'REJECTED', 'COD_COLLECTED', 'EXPIRED')),
  CONSTRAINT payment_transactions_status_check CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'NEED_REVIEW')),
  CONSTRAINT payment_transactions_amount_check CHECK (amount >= 0),
  CONSTRAINT payment_transactions_currency_check CHECK (currency_code = 'VND')
);
CREATE INDEX payment_transactions_payment_id_occurred_at_id_idx ON public.payment_transactions(payment_id, occurred_at DESC, id DESC);
CREATE INDEX payment_transactions_provider_external_id_idx ON public.payment_transactions(provider, external_id);
CREATE UNIQUE INDEX payment_transactions_provider_external_event_id_key
  ON public.payment_transactions(provider, external_event_id)
  WHERE provider IS NOT NULL AND external_event_id IS NOT NULL;

CREATE TABLE public.payment_evidences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id BIGINT NOT NULL,
  media_asset_id BIGINT NOT NULL UNIQUE,
  uploaded_by BIGINT,
  uploader_type VARCHAR(24) NOT NULL,
  guest_access_id VARCHAR(100),
  file_hash VARCHAR(128) NOT NULL,
  note VARCHAR(1000),
  status VARCHAR(24) NOT NULL DEFAULT 'PENDING_REVIEW',
  reviewed_by BIGINT,
  reviewed_at TIMESTAMPTZ(6),
  review_reason VARCHAR(500),
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payment_evidences_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT payment_evidences_media_asset_id_fkey FOREIGN KEY (media_asset_id) REFERENCES public.media_assets(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT payment_evidences_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT payment_evidences_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT payment_evidences_payment_id_file_hash_key UNIQUE (payment_id, file_hash),
  CONSTRAINT payment_evidences_status_check CHECK (status IN ('PENDING_REVIEW', 'ACCEPTED', 'REJECTED')),
  CONSTRAINT payment_evidences_uploader_check CHECK (
    (uploader_type = 'CUSTOMER' AND uploaded_by IS NOT NULL AND guest_access_id IS NULL)
    OR (uploader_type = 'GUEST' AND uploaded_by IS NULL AND guest_access_id IS NOT NULL)
  ),
  CONSTRAINT payment_evidences_review_check CHECK (
    (status = 'PENDING_REVIEW' AND reviewed_by IS NULL AND reviewed_at IS NULL)
    OR (status IN ('ACCEPTED', 'REJECTED') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
  )
);
CREATE INDEX payment_evidences_payment_id_status_created_at_idx ON public.payment_evidences(payment_id, status, created_at DESC);
CREATE INDEX payment_evidences_uploaded_by_idx ON public.payment_evidences(uploaded_by);
CREATE INDEX payment_evidences_reviewed_by_idx ON public.payment_evidences(reviewed_by);

CREATE FUNCTION public.reject_payment_transaction_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'payment_transactions is append-only';
END;
$$;
REVOKE ALL ON FUNCTION public.reject_payment_transaction_mutation() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER payment_transactions_no_update_or_delete
BEFORE UPDATE OR DELETE ON public.payment_transactions
FOR EACH ROW EXECUTE FUNCTION public.reject_payment_transaction_mutation();

CREATE TRIGGER payment_transactions_no_truncate
BEFORE TRUNCATE ON public.payment_transactions
FOR EACH STATEMENT EXECUTE FUNCTION public.reject_payment_transaction_mutation();

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_evidences ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.payments, public.payment_transactions, public.payment_evidences FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;

COMMIT;
