BEGIN;

SELECT pg_advisory_xact_lock(hashtext('dctd:add_stock_transfer_core'));

CREATE TABLE public.stock_transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_no VARCHAR(32) NOT NULL UNIQUE,
  from_warehouse_id BIGINT NOT NULL,
  to_warehouse_id BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
  reason TEXT NOT NULL,
  idempotency_key VARCHAR(150) NOT NULL UNIQUE,
  request_hash CHAR(64) NOT NULL,
  created_by BIGINT NOT NULL,
  submitted_at TIMESTAMPTZ(6),
  shipped_by BIGINT,
  shipped_at TIMESTAMPTZ(6),
  received_by BIGINT,
  received_at TIMESTAMPTZ(6),
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT stock_transfers_warehouses_differ_check CHECK (from_warehouse_id <> to_warehouse_id),
  CONSTRAINT stock_transfers_status_check CHECK (status IN ('DRAFT', 'SUBMITTED', 'SHIPPED', 'RECEIVED')),
  CONSTRAINT stock_transfers_state_timestamps_check CHECK (
    (status = 'DRAFT' AND submitted_at IS NULL AND shipped_at IS NULL AND received_at IS NULL)
    OR (status = 'SUBMITTED' AND submitted_at IS NOT NULL AND shipped_at IS NULL AND received_at IS NULL)
    OR (status = 'SHIPPED' AND submitted_at IS NOT NULL AND shipped_at IS NOT NULL AND shipped_by IS NOT NULL AND received_at IS NULL)
    OR (status = 'RECEIVED' AND submitted_at IS NOT NULL AND shipped_at IS NOT NULL AND shipped_by IS NOT NULL AND received_at IS NOT NULL AND received_by IS NOT NULL)
  ),
  CONSTRAINT stock_transfers_from_warehouse_id_fkey FOREIGN KEY (from_warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT stock_transfers_to_warehouse_id_fkey FOREIGN KEY (to_warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT stock_transfers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT stock_transfers_shipped_by_fkey FOREIGN KEY (shipped_by) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT stock_transfers_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX stock_transfers_from_warehouse_id_status_created_at_idx
  ON public.stock_transfers(from_warehouse_id, status, created_at);
CREATE INDEX stock_transfers_to_warehouse_id_status_created_at_idx
  ON public.stock_transfers(to_warehouse_id, status, created_at);

CREATE TABLE public.stock_transfer_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_transfer_id BIGINT NOT NULL,
  product_variant_id BIGINT NOT NULL,
  requested_qty INTEGER NOT NULL,
  shipped_qty INTEGER NOT NULL DEFAULT 0,
  received_qty INTEGER NOT NULL DEFAULT 0,
  damaged_qty INTEGER NOT NULL DEFAULT 0,
  damage_reason VARCHAR(500),
  CONSTRAINT stock_transfer_items_quantity_check CHECK (
    requested_qty > 0
    AND shipped_qty >= 0 AND shipped_qty <= requested_qty
    AND received_qty >= 0 AND damaged_qty >= 0
    AND received_qty + damaged_qty <= shipped_qty
  ),
  CONSTRAINT stock_transfer_items_damage_reason_check CHECK (
    (damaged_qty = 0 AND damage_reason IS NULL)
    OR (damaged_qty > 0 AND NULLIF(BTRIM(damage_reason), '') IS NOT NULL)
  ),
  CONSTRAINT stock_transfer_items_stock_transfer_id_fkey FOREIGN KEY (stock_transfer_id) REFERENCES public.stock_transfers(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT stock_transfer_items_product_variant_id_fkey FOREIGN KEY (product_variant_id) REFERENCES public.product_variants(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT stock_transfer_items_stock_transfer_id_product_variant_id_key UNIQUE (stock_transfer_id, product_variant_id)
);

CREATE INDEX stock_transfer_items_product_variant_id_idx
  ON public.stock_transfer_items(product_variant_id);

ALTER TABLE public.stock_transfers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_transfer_items ENABLE ROW LEVEL SECURITY;

COMMIT;
