BEGIN;

SELECT pg_advisory_xact_lock(hashtext('dctd:add_fulfillment_foundation'));

CREATE SEQUENCE public.fulfillment_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE public.fulfillments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE,
  warehouse_id BIGINT NOT NULL,
  fulfillment_no VARCHAR(40) NOT NULL UNIQUE,
  status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  carrier_code VARCHAR(64),
  tracking_no VARCHAR(128),
  picked_at TIMESTAMPTZ(6),
  packed_at TIMESTAMPTZ(6),
  shipped_at TIMESTAMPTZ(6),
  delivered_at TIMESTAMPTZ(6),
  delivery_failure_reason_code VARCHAR(64),
  returned_to_warehouse_at TIMESTAMPTZ(6),
  return_condition VARCHAR(24),
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fulfillments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fulfillments_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fulfillments_status_check CHECK (status IN ('PENDING', 'PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNING_TO_WAREHOUSE', 'RETURNED_TO_WAREHOUSE', 'CANCELLED')),
  CONSTRAINT fulfillments_return_condition_check CHECK (return_condition IS NULL OR return_condition IN ('SELLABLE', 'DAMAGED', 'MISSING')),
  CONSTRAINT fulfillments_warehouse_match_check CHECK (warehouse_id > 0),
  CONSTRAINT fulfillments_timestamp_check CHECK (
    (status <> 'PICKING' OR picked_at IS NOT NULL)
    AND (status <> 'PACKED' OR (picked_at IS NOT NULL AND packed_at IS NOT NULL))
    AND (status <> 'SHIPPED' OR shipped_at IS NOT NULL)
    AND (status <> 'DELIVERED' OR delivered_at IS NOT NULL)
    AND (status <> 'RETURNED_TO_WAREHOUSE' OR returned_to_warehouse_at IS NOT NULL)
  )
);
CREATE INDEX fulfillments_warehouse_status_created_idx ON public.fulfillments(warehouse_id, status, created_at DESC, id DESC);
CREATE INDEX fulfillments_status_updated_idx ON public.fulfillments(status, updated_at);
CREATE INDEX fulfillments_tracking_no_idx ON public.fulfillments(tracking_no);

CREATE TABLE public.fulfillment_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fulfillment_id BIGINT NOT NULL,
  sequence_no INTEGER NOT NULL,
  from_status VARCHAR(40),
  to_status VARCHAR(40) NOT NULL,
  reason VARCHAR(500),
  actor_id BIGINT,
  request_id VARCHAR(100) NOT NULL,
  idempotency_key VARCHAR(150),
  request_hash CHAR(64),
  metadata_json JSONB,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fulfillment_history_fulfillment_id_fkey FOREIGN KEY (fulfillment_id) REFERENCES public.fulfillments(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fulfillment_history_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fulfillment_history_sequence_check CHECK (sequence_no > 0),
  CONSTRAINT fulfillment_history_status_check CHECK (to_status IN ('PENDING', 'PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNING_TO_WAREHOUSE', 'RETURNED_TO_WAREHOUSE', 'CANCELLED')),
  CONSTRAINT fulfillment_history_idempotency_pair_check CHECK ((idempotency_key IS NULL) = (request_hash IS NULL)),
  CONSTRAINT fulfillment_history_fulfillment_sequence_key UNIQUE (fulfillment_id, sequence_no),
  CONSTRAINT fulfillment_history_fulfillment_idempotency_key UNIQUE (fulfillment_id, idempotency_key)
);
CREATE INDEX fulfillment_history_fulfillment_created_idx ON public.fulfillment_status_history(fulfillment_id, created_at);
CREATE INDEX fulfillment_history_request_id_idx ON public.fulfillment_status_history(request_id);
CREATE INDEX fulfillment_history_actor_id_idx ON public.fulfillment_status_history(actor_id);

INSERT INTO public.fulfillments (
  order_id, warehouse_id, fulfillment_no, status,
  picked_at, packed_at, shipped_at, delivered_at, returned_to_warehouse_at,
  created_at, updated_at
)
SELECT order_row.id,
       order_row.warehouse_id,
       'FUL-' || order_row.order_no,
       CASE order_row.fulfillment_status
         WHEN 'FAILED' THEN 'DELIVERY_FAILED'
         WHEN 'RETURNED' THEN 'RETURNED_TO_WAREHOUSE'
         ELSE order_row.fulfillment_status
       END,
       CASE WHEN order_row.fulfillment_status IN ('PICKING', 'PACKED', 'SHIPPED', 'DELIVERED', 'FAILED', 'RETURNED') THEN order_row.updated_at END,
       CASE WHEN order_row.fulfillment_status IN ('PACKED', 'SHIPPED', 'DELIVERED', 'FAILED', 'RETURNED') THEN order_row.updated_at END,
       CASE WHEN order_row.fulfillment_status IN ('SHIPPED', 'DELIVERED', 'FAILED', 'RETURNED') THEN order_row.updated_at END,
       CASE WHEN order_row.fulfillment_status = 'DELIVERED' THEN order_row.updated_at END,
       CASE WHEN order_row.fulfillment_status = 'RETURNED' THEN order_row.updated_at END,
       order_row.created_at,
       order_row.updated_at
FROM public.orders order_row
ON CONFLICT (order_id) DO NOTHING;

INSERT INTO public.fulfillment_status_history (
  fulfillment_id, sequence_no, from_status, to_status, reason, request_id, created_at
)
SELECT fulfillment.id, 1, NULL, fulfillment.status, 'Backfill từ Order hiện hữu',
       'migration:20260912020000', fulfillment.created_at
FROM public.fulfillments fulfillment
WHERE NOT EXISTS (
  SELECT 1 FROM public.fulfillment_status_history history WHERE history.fulfillment_id = fulfillment.id
);

CREATE FUNCTION public.reject_fulfillment_history_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'fulfillment_status_history is append-only';
END;
$$;
REVOKE ALL ON FUNCTION public.reject_fulfillment_history_mutation() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER fulfillment_history_no_update_or_delete
BEFORE UPDATE OR DELETE ON public.fulfillment_status_history
FOR EACH ROW EXECUTE FUNCTION public.reject_fulfillment_history_mutation();

CREATE TRIGGER fulfillment_history_no_truncate
BEFORE TRUNCATE ON public.fulfillment_status_history
FOR EACH STATEMENT EXECUTE FUNCTION public.reject_fulfillment_history_mutation();

ALTER TABLE public.fulfillments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fulfillment_status_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE public.fulfillments, public.fulfillment_status_history FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.fulfillment_number_seq FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;

COMMIT;
