export const PAYMENT_METHOD = {
  BANK_TRANSFER: 'BANK_TRANSFER',
  COD: 'COD',
} as const;

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  AWAITING_CONFIRMATION: 'AWAITING_CONFIRMATION',
  NEED_REVIEW: 'NEED_REVIEW',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;

export const PAYMENT_EVIDENCE_STATUS = {
  PENDING_REVIEW: 'PENDING_REVIEW',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const PAYMENT_TRANSACTION_TYPE = {
  CREATED: 'CREATED',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  COD_COLLECTED: 'COD_COLLECTED',
  EXPIRED: 'EXPIRED',
} as const;

export const PAYMENT_PROVIDER = {
  MANUAL_BANK_TRANSFER: 'MANUAL_BANK_TRANSFER',
  INTERNAL_COD: 'INTERNAL_COD',
} as const;

export const PAYMENT_TRANSACTION = {
  MAX_WAIT_MS: 10_000,
  TIMEOUT_MS: 30_000,
  MAX_SERIALIZATION_RETRIES: 3,
} as const;
