BEGIN;

SELECT pg_advisory_xact_lock(hashtext('dctd:persist_cms_and_reviews'));

-- CMS Content và Product Reviews trước đây là vertical slice in-memory: dữ liệu nằm
-- trong mảng hằng của tiến trình nên mất sạch mỗi lần khởi động lại và lệch nhau khi
-- chạy nhiều tiến trình. Contract OpenAPI giữ nguyên; chỉ đổi nơi lưu.
--
-- Các cột "đích" (cover_asset_id, product_id, customer_id, order_item_id, moderated_by)
-- giữ đúng tên trong `document/09-v1-model.dbml` nhưng NULLABLE ở V1, vì luồng tạo
-- review theo order_item đã mua và luồng upload ảnh bìa qua media asset chưa tồn tại.
-- Khi hai luồng đó ra đời thì backfill rồi siết NOT NULL, không phải đổi tên cột.

CREATE TABLE public.posts (
  "id"                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "post_type"             VARCHAR(32) NOT NULL,
  "slug"                  VARCHAR(255) NOT NULL,
  "title"                 VARCHAR(255) NOT NULL,
  "excerpt"               TEXT NOT NULL,
  "body"                  TEXT NOT NULL,
  "cover_url"             TEXT NOT NULL,
  "cover_asset_id"        BIGINT,
  "related_product_slugs" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "status"                VARCHAR(24) NOT NULL DEFAULT 'PUBLISHED',
  "published_at"          TIMESTAMPTZ(6) NOT NULL,
  "archived_at"           TIMESTAMPTZ(6),
  "archive_reason"        VARCHAR(255),
  "version"               BIGINT NOT NULL DEFAULT 0,
  "created_at"            TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"            TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "posts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "posts_post_type_check"
    CHECK ("post_type" IN ('NEWS', 'TRAINING_GUIDE', 'PRODUCT_GUIDE', 'ABOUT')),
  CONSTRAINT "posts_status_check"
    CHECK ("status" IN ('PUBLISHED', 'ARCHIVED')),
  -- Archive là transition một chiều: đã archive thì bắt buộc có thời điểm và lý do.
  CONSTRAINT "posts_archive_shape_check"
    CHECK (("status" = 'ARCHIVED') = ("archived_at" IS NOT NULL AND "archive_reason" IS NOT NULL)),
  CONSTRAINT "posts_related_slugs_is_array_check"
    CHECK (jsonb_typeof("related_product_slugs") = 'array')
);

CREATE UNIQUE INDEX "posts_slug_key" ON public.posts("slug");
CREATE INDEX "posts_status_published_at_id_idx"
  ON public.posts("status", "published_at" DESC, "id" DESC);
CREATE INDEX "posts_post_type_status_idx" ON public.posts("post_type", "status");
CREATE INDEX "posts_cover_asset_id_idx" ON public.posts("cover_asset_id");

ALTER TABLE public.posts ADD CONSTRAINT "posts_cover_asset_id_fkey"
  FOREIGN KEY ("cover_asset_id") REFERENCES public.media_assets("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE public.product_reviews (
  "id"                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "product_slug"           VARCHAR(255) NOT NULL,
  "product_id"             BIGINT,
  "customer_display_name"  VARCHAR(255) NOT NULL,
  "customer_id"            BIGINT,
  "order_item_id"          BIGINT,
  "rating"                 SMALLINT NOT NULL,
  "title"                  VARCHAR(255) NOT NULL,
  "content"                TEXT NOT NULL,
  "verified_purchase"      BOOLEAN NOT NULL DEFAULT false,
  "status"                 VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  "moderation_reason"      TEXT,
  "moderated_at"           TIMESTAMPTZ(6),
  "moderated_by"           BIGINT,
  "version"                BIGINT NOT NULL DEFAULT 0,
  "created_at"             TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"             TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "product_reviews_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "product_reviews_rating_check" CHECK ("rating" BETWEEN 1 AND 5),
  CONSTRAINT "product_reviews_status_check"
    CHECK ("status" IN ('PENDING', 'APPROVED', 'REJECTED')),
  -- Đã kiểm duyệt thì phải có mốc thời gian; PENDING thì chưa.
  CONSTRAINT "product_reviews_moderation_shape_check"
    CHECK (("status" = 'PENDING') = ("moderated_at" IS NULL)),
  -- verified_purchase chỉ được đúng khi có order_item thật đứng sau.
  CONSTRAINT "product_reviews_verified_requires_order_item_check"
    CHECK ("verified_purchase" = false OR "order_item_id" IS NOT NULL)
);

CREATE UNIQUE INDEX "product_reviews_order_item_id_key"
  ON public.product_reviews("order_item_id") WHERE "order_item_id" IS NOT NULL;
CREATE INDEX "product_reviews_product_slug_status_created_at_idx"
  ON public.product_reviews("product_slug", "status", "created_at" DESC);
CREATE INDEX "product_reviews_status_created_at_id_idx"
  ON public.product_reviews("status", "created_at" DESC, "id" DESC);
CREATE INDEX "product_reviews_product_id_idx" ON public.product_reviews("product_id");
CREATE INDEX "product_reviews_customer_id_idx" ON public.product_reviews("customer_id");
CREATE INDEX "product_reviews_order_item_id_idx" ON public.product_reviews("order_item_id");
CREATE INDEX "product_reviews_moderated_by_idx" ON public.product_reviews("moderated_by");

ALTER TABLE public.product_reviews ADD CONSTRAINT "product_reviews_product_id_fkey"
  FOREIGN KEY ("product_id") REFERENCES public.products("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE public.product_reviews ADD CONSTRAINT "product_reviews_customer_id_fkey"
  FOREIGN KEY ("customer_id") REFERENCES public.customers("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE public.product_reviews ADD CONSTRAINT "product_reviews_order_item_id_fkey"
  FOREIGN KEY ("order_item_id") REFERENCES public.order_items("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE public.product_reviews ADD CONSTRAINT "product_reviews_moderated_by_fkey"
  FOREIGN KEY ("moderated_by") REFERENCES public.users("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE public.product_review_comments (
  "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "product_review_id" BIGINT NOT NULL,
  "author_type"       VARCHAR(24) NOT NULL,
  "author_name"       VARCHAR(255) NOT NULL,
  "author_user_id"    BIGINT,
  "content"           TEXT NOT NULL,
  "status"            VARCHAR(24) NOT NULL DEFAULT 'PUBLISHED',
  "version"           BIGINT NOT NULL DEFAULT 0,
  "created_at"        TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at"        TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "product_review_comments_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "product_review_comments_author_type_check"
    CHECK ("author_type" IN ('CUSTOMER', 'STAFF')),
  CONSTRAINT "product_review_comments_status_check"
    CHECK ("status" IN ('PUBLISHED', 'HIDDEN')),
  -- Trả lời của nhân viên phải truy ra được người thật.
  CONSTRAINT "product_review_comments_staff_requires_user_check"
    CHECK ("author_type" <> 'STAFF' OR "author_user_id" IS NOT NULL)
);

CREATE INDEX "product_review_comments_review_created_at_idx"
  ON public.product_review_comments("product_review_id", "created_at");
CREATE INDEX "product_review_comments_author_user_id_idx"
  ON public.product_review_comments("author_user_id");

ALTER TABLE public.product_review_comments ADD CONSTRAINT "product_review_comments_product_review_id_fkey"
  FOREIGN KEY ("product_review_id") REFERENCES public.product_reviews("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE public.product_review_comments ADD CONSTRAINT "product_review_comments_author_user_id_fkey"
  FOREIGN KEY ("author_user_id") REFERENCES public.users("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Deny-by-default như mọi base table khác; migration rls_coverage_guard sẽ kiểm lại.
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_review_comments ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON public.posts, public.product_reviews, public.product_review_comments
  FROM anon, authenticated;

COMMIT;
