import { Permission } from './iam.types';

export const PERMISSION_CATALOG: readonly Permission[] = [
  { code: 'system.module.view', module: 'System', action: 'view', sensitive: false },
  { code: 'org.branch.view', module: 'Organization', action: 'view', sensitive: false },
  { code: 'org.branch.manage', module: 'Organization', action: 'manage', sensitive: true },
  { code: 'org.warehouse.view', module: 'Organization', action: 'view', sensitive: false },
  { code: 'org.warehouse.manage', module: 'Organization', action: 'manage', sensitive: true },
  { code: 'iam.user.view', module: 'IAM', action: 'view', sensitive: true },
  { code: 'iam.user.manage', module: 'IAM', action: 'manage', sensitive: true },
  { code: 'iam.role.view', module: 'IAM', action: 'view', sensitive: false },
  { code: 'iam.role.manage', module: 'IAM', action: 'manage', sensitive: true },
  { code: 'iam.assignment.manage', module: 'IAM', action: 'manage', sensitive: true },
  { code: 'iam.audit.view', module: 'IAM', action: 'view', sensitive: true },
  { code: 'customer.view', module: 'Customer', action: 'view', sensitive: true },
  { code: 'customer.manage', module: 'Customer', action: 'manage', sensitive: true },
  { code: 'catalog.brand.view', module: 'Catalog', action: 'view', sensitive: false },
  { code: 'catalog.brand.manage', module: 'Catalog', action: 'manage', sensitive: false },
  { code: 'catalog.category.view', module: 'Catalog', action: 'view', sensitive: false },
  { code: 'catalog.category.manage', module: 'Catalog', action: 'manage', sensitive: false },
  { code: 'catalog.product.view', module: 'Catalog', action: 'view', sensitive: false },
  { code: 'catalog.product.manage', module: 'Catalog', action: 'manage', sensitive: false },
  { code: 'catalog.product.publish', module: 'Catalog', action: 'publish', sensitive: true },
  { code: 'catalog.price.view', module: 'Pricing', action: 'view', sensitive: false },
  { code: 'catalog.price.manage', module: 'Pricing', action: 'manage', sensitive: true },
  { code: 'review.moderate', module: 'Review', action: 'moderate', sensitive: true },
  { code: 'inventory.stock.view', module: 'Inventory', action: 'view', sensitive: false },
  { code: 'inventory.stock.adjust', module: 'Inventory', action: 'adjust', sensitive: true },
  { code: 'inventory.stocktake.manage', module: 'Inventory', action: 'manage', sensitive: true },
  { code: 'order.view', module: 'Order', action: 'view', sensitive: true },
  { code: 'order.manage', module: 'Order', action: 'manage', sensitive: true },
  { code: 'payment.view', module: 'Payment', action: 'view', sensitive: true },
  { code: 'payment.confirm', module: 'Payment', action: 'confirm', sensitive: true },
  { code: 'fulfillment.view', module: 'Fulfillment', action: 'view', sensitive: false },
  { code: 'fulfillment.pick', module: 'Fulfillment', action: 'pick', sensitive: true },
  { code: 'fulfillment.pack', module: 'Fulfillment', action: 'pack', sensitive: true },
  { code: 'fulfillment.ship', module: 'Fulfillment', action: 'ship', sensitive: true },
  { code: 'return.view', module: 'Return', action: 'view', sensitive: true },
  { code: 'return.decide', module: 'Return', action: 'decide', sensitive: true },
  { code: 'return.receive', module: 'Return', action: 'receive', sensitive: true },
  { code: 'content.post.view', module: 'CMS', action: 'view', sensitive: false },
  { code: 'content.post.manage', module: 'CMS', action: 'manage', sensitive: true },
  { code: 'media.asset.upload', module: 'Media', action: 'upload', sensitive: true },
  { code: 'media.asset.view', module: 'Media', action: 'view', sensitive: false },
  { code: 'media.asset.manage', module: 'Media', action: 'manage', sensitive: true },
  { code: 'report.operation.view', module: 'Reporting', action: 'view', sensitive: false },
  { code: 'report.revenue.view', module: 'Reporting', action: 'view', sensitive: true },
  { code: 'report.inventory.view', module: 'Reporting', action: 'view', sensitive: false },
] as const;

const permissionCodes = (...codes: string[]): readonly string[] => codes;

export const V1_ROLE_PERMISSIONS = {
  OWNER: PERMISSION_CATALOG.map(({ code }) => code),
  BRANCH_MANAGER: permissionCodes(
    'org.branch.view',
    'org.warehouse.view',
    'iam.user.view',
    'iam.user.manage',
    'iam.role.view',
    'iam.assignment.manage',
    'customer.view',
    'customer.manage',
    'catalog.brand.view',
    'catalog.category.view',
    'catalog.product.view',
    'catalog.price.view',
    'review.moderate',
    'inventory.stock.view',
    'inventory.stock.adjust',
    'inventory.stocktake.manage',
    'order.view',
    'order.manage',
    'payment.view',
    'payment.confirm',
    'fulfillment.view',
    'fulfillment.pick',
    'fulfillment.pack',
    'fulfillment.ship',
    'return.view',
    'return.decide',
    'return.receive',
    'report.operation.view',
    'report.revenue.view',
    'report.inventory.view',
  ),
  STAFF: permissionCodes(
    'org.branch.view',
    'org.warehouse.view',
    'customer.view',
    'catalog.brand.view',
    'catalog.category.view',
    'catalog.product.view',
    'catalog.price.view',
    'inventory.stock.view',
    'inventory.stocktake.manage',
    'order.view',
    'order.manage',
    'fulfillment.view',
    'fulfillment.pick',
    'fulfillment.pack',
    'fulfillment.ship',
    'return.view',
    'return.receive',
  ),
} as const;
