import { Permission } from './iam.types';

export const PERMISSION_CATALOG: readonly Permission[] = [
  { code: 'org.branch.view', module: 'Organization', action: 'view', sensitive: false },
  { code: 'org.branch.manage', module: 'Organization', action: 'manage', sensitive: true },
  { code: 'org.warehouse.view', module: 'Organization', action: 'view', sensitive: false },
  { code: 'org.warehouse.manage', module: 'Organization', action: 'manage', sensitive: true },
  { code: 'iam.user.view', module: 'IAM', action: 'view', sensitive: true },
  { code: 'iam.user.manage', module: 'IAM', action: 'manage', sensitive: true },
  { code: 'iam.role.view', module: 'IAM', action: 'view', sensitive: false },
  { code: 'iam.role.manage', module: 'IAM', action: 'manage', sensitive: true },
  { code: 'iam.assignment.manage', module: 'IAM', action: 'manage', sensitive: true },
  { code: 'iam.audit.view', module: 'IAM', action: 'view', sensitive: true },
  { code: 'catalog.brand.view', module: 'Catalog', action: 'view', sensitive: false },
  { code: 'catalog.brand.manage', module: 'Catalog', action: 'manage', sensitive: false },
  { code: 'catalog.category.view', module: 'Catalog', action: 'view', sensitive: false },
  { code: 'catalog.category.manage', module: 'Catalog', action: 'manage', sensitive: false },
  { code: 'catalog.product.view', module: 'Catalog', action: 'view', sensitive: false },
  { code: 'catalog.product.manage', module: 'Catalog', action: 'manage', sensitive: false },
  { code: 'catalog.product.publish', module: 'Catalog', action: 'publish', sensitive: true },
  { code: 'catalog.price.view', module: 'Pricing', action: 'view', sensitive: false },
  { code: 'catalog.price.manage', module: 'Pricing', action: 'manage', sensitive: true },
  { code: 'media.asset.upload', module: 'Media', action: 'upload', sensitive: true },
  { code: 'media.asset.view', module: 'Media', action: 'view', sensitive: false },
  { code: 'media.asset.manage', module: 'Media', action: 'manage', sensitive: true },
] as const;
