export const SHIPPING_RULE_STATUS = {
  ACTIVE: 'ACTIVE',
} as const;

export const SHIPPING_CURRENCY = 'VND' as const;

export const SHIPPING_METHOD = {
  BRANCH_FREE: 'BRANCH_FREE',
  STANDARD_DELIVERY: 'STANDARD_DELIVERY',
  THIRD_PARTY: 'THIRD_PARTY',
  MANUAL_EXTERNAL: 'MANUAL_EXTERNAL',
} as const;
